/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '2/17/24, 2:01 PM' 
 * Generated by 'madha' 
 * Generated on server 'MADHAVI_REDDY.HSD1.CT.COMCAST.NET.' 
 * Generated on SAS platform 'X64_10HOME WIN' 
 * Generated on SAS version '9.04.01M6P11152018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36' 
 * Generated on web client 'http://localhost:51790/main?locale=en_IN&zone=GMT-05%253A00&sutoken=%257B347C4535-702D-441D-97CF-99A6CF5017C2%257D' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=PROJECT.MONTHLYDATASET out=Work.preProcessedData;
	by date;
run;

proc arima data=Work.preProcessedData plots
     (only)=(series(corr crosscorr) residual(corr normal) 
		forecast(forecast forecastonly) );
	identify var=pollution(12);
	estimate method=ML outstat=work.outstat0001;
	forecast lead=2 back=2 alpha=0.05 id=date interval=month;
	outlier;
	run;
quit;

proc delete data=Work.preProcessedData;
run;