/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '2/17/24, 12:37 PM' 
 * Generated by 'madha' 
 * Generated on server 'MADHAVI_REDDY.HSD1.CT.COMCAST.NET.' 
 * Generated on SAS platform 'X64_10HOME WIN' 
 * Generated on SAS version '9.04.01M6P11152018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36' 
 * Generated on web client 'http://localhost:51790/main?locale=en_IN&zone=GMT-05%253A00&sutoken=%257B347C4535-702D-441D-97CF-99A6CF5017C2%257D&openfile=C%253A%255CUsers%255Cmadha%255CAppData%255CLocal%255CMicrosoft%255CWindows%255CINetCache%255CIE%255C44OCU05A%255CTime_Series_Data_Preparation%255B1%255D.ctk' 
 *
 */

ods noproctitle;

proc sort data=PROJECT.DATASET out=Work.preProcessedData;
	by date;
run;

proc timedata data=Work.preProcessedData seasonality=12 out=WORK._tsoutput;
	id date interval=month setmissing=previous;
	var pollution / accumulate=average transform=none;
	var dew / accumulate=average transform=none;
	var temp / accumulate=average transform=none;
	var press / accumulate=average transform=none;
	var wnd_spd / accumulate=average transform=none;
	var snow / accumulate=total transform=none;
	var rain / accumulate=total transform=none;
run;

data PROJECT.MONTHLYDATASET(rename=());
	set WORK._tsoutput;
run;

proc delete data=Work.preProcessedData;
run;

proc delete data=WORK._tsoutput;
run;