/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '2/17/24, 12:41 PM' 
 * Generated by 'madha' 
 * Generated on server 'MADHAVI_REDDY.HSD1.CT.COMCAST.NET.' 
 * Generated on SAS platform 'X64_10HOME WIN' 
 * Generated on SAS version '9.04.01M6P11152018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36' 
 * Generated on web client 'http://localhost:51790/main?locale=en_IN&zone=GMT-05%253A00&sutoken=%257B347C4535-702D-441D-97CF-99A6CF5017C2%257D' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=PROJECT.MONTHLYDATASET out=Work.preProcessedData;
	by date;
run;

proc timeseries data=Work.preProcessedData seasonality=12 plots=(series cycles 
		corr decomp tc sc) crossplots=(series);
	id date interval=month;
	var pollution / accumulate=none transform=none dif=0 sdif=0;
	crossvar dew / accumulate=none transform=none dif=0 sdif=0;
	crossvar temp / accumulate=none transform=none dif=0 sdif=0;
	crossvar press / accumulate=none transform=none dif=0 sdif=0;
	crossvar wnd_spd / accumulate=none transform=none dif=0 sdif=0;
	crossvar snow / accumulate=none transform=none dif=0 sdif=0;
	crossvar rain / accumulate=none transform=none dif=0 sdif=0;
	decomp tc seasonal / mode=multoradd;
run;

/* Unit root test analysis */
proc arima data=Work.preProcessedData plots=none;
	ods select StationarityTests;
	identify var=pollution stationarity=(adf=2);
	run;
quit;

proc delete data=Work.preProcessedData;
run;